name             'mycookbook'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures mycookbook'
long_description 'Installs/Configures mycookbook'
version          '0.1.0'
